apiVersion: v1
kind: Service
metadata:
  name: log-message-processor
  namespace: argocd 
spec:
  type: ClusterIP
  selector:
    app: log-message-processor
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

