apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: argocd 

spec:
  type: ClusterIP
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 8083  # Port interne du cluster
      targetPort: 8083  # Port exposé par le conteneur

