apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: argocd 

spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: moutchou/k8sprojet-users-api
        ports:
        - containerPort: 8083
        env:
        - name: ZIPKIN_SERVER_URL
          value: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"  # URL du service Zipkin


