apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30099  # Choisissez un port dans la plage 30000-32767
  type: NodePort

